### ISSUE TITLE
partial generation

### ISSUE THREAD

**Issue by amery** [karasz/gomesh#4]
hi, can we have a mechanism to generate a subset of the config for a given node?
e.g. `gomesh generate $(hostname)`

**Comment by karasz** [comment]
Hi,
it can be done, the only thing is that gomesh has no real knowledge about `$(hostname)` it only knows the name that is given to each wireguard peer so actually the command would be `gomesh generate $(peername)`. Regarding functionality I think that the `$(peername)` should be an optional flag which if missing will force gomesh to generate the whole config.

Is that what you had in mind?

**Comment by amery** [comment]
I might have wrongly understood generate as for all hosts instead of for all peers. mixing up the network manager with gomesh.
