### ISSUE TITLE
config generate , and what ?

### ISSUE THREAD

**Issue by changchichung** [karasz/gomesh#8]
so I run gomesh to generate a database.json like
```
    {
        "Name": "30_net",
        "PrivateKey": "MPKgI4vezUhpJQb+2OA231elwAdvpfqJ+4GTKFyhgm4=",
        "Address": [
            "10.1.30.1"
        ],
        "ListenPort": 12000,
        "Endpoint": "30.30.30.30",
        "AllowedIPs": [],
        "FwMark": 0,
        "DNS": "",
        "MTU": 0,
        "Table": "",
        "PreUp": "",
        "PostUp": "",
        "PreDown": "",
        "PostDown": "",
        "SaveConfig": false
    }
```
and what's the next step ?? how do I create/join a wireguard mesh network ?

**Comment by karasz** [comment]
1. Gomesh is a tool in alpha stage without all the needed functionality yet. It roughly works.
2. Gomesh is just a tool to generate wireguard config files it is not a wireguard implementation in Go.
3. You need at least two items in the database file. 
After that you need to run gomesh generate to actually generate the config files. The config files need to be moved to the machines that will be part of the wireguard mesh (for example under the name ```/etc/wireguard/wg0.conf```). After that you can start the wireguard daemon on each machine using ```systemctl start wg-quick@wg0```
